travis:
  secure:
    BINSTAR_TOKEN: HQrLyTqwzQ/IECYRxZ1i3cAjayy7ydM0049MDmsHM4rJ4w/Ld64SpRgz8E38zD2JAPEebRp68NNWIIQi1TuwdCqeCgcukXlrVtsekJq4R+Wza3KjpG6EepoSjO4VuE7hHwMrbYP15HJQM+LHI9Jmti1/FBDPGDH+QiJv9PIBaHjsdD1dxu7OC68tRLcO9aATXw7C/S7JQIlGaNjEABKRZqkDMwNqaIvNHhsq6spXmeM8d5fKjMXf5CEOpxVJ1OVNGfPB/ipD0Sj5x+g6TYy4BxZD3GhzsSTazzVfIwLNJ09CEqvYT0OvQAwBa75jHlLmMbEcFLqs4YoK8n7F7CQ/hVaaCmALn1QqEV3N2XN8pBqPpKoyYtQc/Fwlf6ncIo5VrZSXvofqJ2/Rq+hVnOWBrlHIN4A0f5DlWOTXstsWWHf2xFio9bW/yi+vq0KzcrDldu/aUBw8czuWewBoPVYKe8OhxdAYKKEWiZxlfL1ePwcuuHHYzEb//uPvaa+ox48wuoeRLy0pXIHmBGItyEf58pnagdoJMPGwq3UgHz8Cx6WqMXJyaeTGeZEcKDWbE7b7aZgvPLr3j6Jyu/y9BC7fnFQw18094m4SgpGLmxKBRstXF8m1x/6S+eT70yLj1oHNd1wIOn3iMBlnhmHmCLcL/ryTqiMFh8J1uEnGbL4nm9o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
