appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RrhiNI+JGSZNucRnrnmHniw8AUe5+xz8yBuWfvpwUeNrGRno7uvwHwysoMEGkb0p76PTzVdpTUfk+kRQhUMrZF/Ehzmza9qdD0XgwT2aOWETxxv2AqeLnerSo3uwBFuabRV3rQ5fNZOgmvhpr7gCc5p8wmTlD0cnn/5GMNs2hnnIVJUGBsmlkfC59GG+DczWpwgjRj94FWgxulo1BUgeVdqOhQ7SVPSzmf7aL5fOHkQILYrQr9hhE276PUa3+u4v0kdTxrn8AGnlehd4b55R4yfNE6COAV8RMKhMHUbqETYc9jWpi9BRDQSw5CTcdD8K30eYMIaSJoRDwSUNwFc0dnQW0h7eRZcBhKefSe+iILQAEk3astzzNDnhSpumFZ+WNujBhyW6NHHp8dk57T2Hulci4wKNg6M89Qtr7nDHBXPbGNcs+RorOH05Tv5Lt0OE2OGzAC1WzajEQ1W4+QE59FdYhT9D2e75EnEVIyhnIbCXA7Dp85KdCBMH1SkeI1A4QjQzd7NkkUONbL8rTACQ8FoKaKeO613dBLXE1QCNFpFSFnQrWUYPa69CGKMMlhSJJAKFl9erBDQJkWUeBX5JcirsU9s2VPHJ8OzzT3aH6WznYzRENGIbnoVJL6IAaaJVSnTTqokuyKkxuVa3kV0UitVM7ObGMwpiXzlNNTCAt3g=}
conda_forge_output_validation: true
